name:                squasher
version:             0.1.0.0
github:              "githubuser/squasher"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/squasher#readme>

dependencies:
- base >= 4.10 && < 5
- text >= 1.2.5.0
- bytestring >= 0.11.4.0
- containers >= 0.6.5.1
- uniplate >= 1.6.13
- binary >= 0.8.9.0
- transformers >= 0.5.6
- equivalence >= 0.4.1
- unordered-containers >= 0.2.19.1 
- hashable >=1.2.5 && <1.5
- STMonadTrans >= 0.4.7
- Erlang >= 0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  squasher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O
    - -optc-ffast-math
    - -optc-O3
    - -fexcess-precision
    dependencies:
    - squasher
    - optparse-applicative

tests:
  squasher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - squasher